apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html

  initContainers:
  - name: init-container
    image: busybox:latest
    command: ['sh', '-c', 'echo "Hello, World!.....let Play" > /work-dir/index.html']
    volumeMounts:
    - name: html-volume
      mountPath: /work-dir

  volumes:
  - name: html-volume
    emptyDir: {}

# Other Pod specifications go here

